name: meso-py312
channels:
  - conda-forge
  - defaults
dependencies:
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - eccodes=2.37.0
  - fonttools=4.53.1
  - freetype=2.12.1
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - jasper=4.2.4
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.10.1
  - libcxx=19.1.0
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.44
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzip=1.11.1
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - munkres=1.1.4
  - ncurses=6.5
  - numba=0.59.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pillow=10.4.0
  - pip=24.2
  - proj=9.5.0
  - pthread-stubs=0.4
  - pycparser=2.22
  - pygrib=2.1.5
  - pyparsing=3.1.4
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.5
  - python-dateutil=2.9.0
  - python_abi=3.12
  - pytz=2024.2
  - readline=8.2
  - requests=2.31.0
  - scipy=1.12.0
  - setuptools=74.1.2
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.46.1
  - tk=8.6.13
  - tornado=6.4.1
  - tzdata=2024a
  - urllib3=2.2.3
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - timeout-decorator==0.5.0
